; LilyGo T3 LoRa32 V1.6.1 — 433 MHz SX1278
; PlatformIO board ID: ttgo-lora32-v21 (T3 v1.6.1 ile uyumlu)

[env:t3]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D T3_V1_6_SX1278

lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    olikraus/U8g2 @ ^2.35.19

build_src_filter = +<*> -<.git/>
