; M5Stack Cardputer + LoRaE220-433 UART modülü (Grove port)

[env:cardputer]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

build_flags =
    -D ESP32S3
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_M5CARDPUTER

lib_deps =
    m5stack/M5Unified @ ^0.2.2
    m5stack/M5Cardputer @ ^1.0.3
    https://github.com/m5stack/M5-LoRa-E220.git

build_src_filter = +<*> -<.git/>
